### ISSUE TITLE
Issues for how to generate the common feature set In the heterogeneous scenario

### ISSUE THREAD

**Issue by qy201706** [pajola/XeNIDS#1]
### After reading your high level paper, I have an issue for 'Standardize'. 

> Did you collect the features values according to the common feature set manually? If I only got CSV files from diferent datasets, it would be a large workload.

**Comment by pajola** [comment]
Thank you for raising this issue. 

The "standardize" step of our framework is essential to proceed with the rest of the pipeline.
The standardization is nothing more than a feature engineering step where, given a set of NIDS datasets, you transform them in such a way that features (and their measure units) are the same. 
We provided a detailed guideline in Appendix.B. 

Let us know if this clarifies your issue.

**Comment by qy201706** [comment]
Thanks for answering my issue.

It's my fault that I broswered  Appendix.B too fast...but after rereading the Appendix.B I get some new issues: 
1. why not implement some feature selection strategies for the base datasets from different netflow tools and choose the common part as the common feature sets. 
2. there too many bool and category type feature in it, the model must be easily trained and also get a much more likely to overfit, although these types of features could be easily collected from heterogeneous scenario.

Look forward to your reply.

**Comment by pajola** [comment]
Answering Q1, you can definitely find automation in the procedure. However, you just need to keep in mind that different datasets might use different names for the same features, or even the same features might be expressed with different units (e.g., KB rather than MB). 

Answering to Q2, by looking to Table 4, you can see that we actually used 3 booleans, 2 categorical, and 7 numerical features. Possible overfitting patterns should be prevented with a proper model validation strategy.

**Comment by qy201706** [comment]
Thanks you very much for your patience.
